[package]
name = "sundial"
version = "0.1.0"
authors = ["shiveen <shiveen.pandita@ordermentum.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
serde_json = "1.0"
pest = "2.1.0"
pest_derive = "2.0"
